export const cardData = [
  {
    id: 6,
    projectName: 'Shorting Hat',
    companyName: '@iot83',
    image: require('../../images/sorting-hat/shorting-hat-login.png'),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 1,
    projectName: 'Seimens',
    companyName: '@iot83',
    image: require("../../images/siemens/seimens1.png"),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 2,
    projectName: 'Flex MLOps',
    companyName: '@iot83',
    image: require('../../images/flexv6login.png'),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 3,
    projectName: 'Application Enablement platform',
    companyName: '@iot83',
    image: require('../../images/Application.png'),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 4,
    projectName: 'OEDC',
    companyName: '@iot83',
    image: require('../../images/oedc/oedc-login.png'),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 5,
    projectName: 'SGRM',
    companyName: '@iot83',
    image: require('../../images/oedc/oedc-login.png'),
    react: '#React',
    html: '#HTML5',
    framework: '#BootStrap',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },

  {
    id: 7,
    projectName: 'Eaton DLM',
    companyName: '@iot83',
    image: require('../../images/eaton-dlm/dlm-login.png'),
    react: '#React',
    typeScript: '#TypeScrip',
    html: '#HTML5',
    framework: '#MUI',
    eatonLibrary: '#Brightlayer UI',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 8,
    projectName: 'Sales Portfolio',
    companyName: '@iot83',
    image: require('../../images/sales-portfolio/sales-portfolio-login.png'),
    react: '#React',
    typeScript: '#JavaScrip',
    html: '#HTML5',
    framework: '#MUI',
    eatonLibrary: '#Brightlayer UI',
    scss: '#Scss',
    amCharts: '#AmCharts',
    designStatus: "Dashboard",
  },
  {
    id: 9,
    projectName: 'ARM-DLM-WEB',
    companyName: '@iot83',
    image: require('../../images/arm-dlm/dlm-login.png'),
    react: '#React',
    typeScript: '#TypeScrip',
    html: '#HTML5',
    framework: '#MUI',
    eatonLibrary: '#Brightlayer UI',
    scss: '#Scss',
    amCharts: '#HighCharts',
    designStatus: "Dashboard",
  },
]